In [10]:
from audioop import avg

import pandas as pd
import simpful as sf
from numpy.f2py import rules
from simpful import Triangular_MF, FuzzySet, Gaussian_MF
from imblearn.under_sampling import RandomUnderSampler

from OccupancyFuzzyClassifier import  OccupancyFuzzyClassifier

In [12]:
clf = OccupancyFuzzyClassifier(under_sample_size=600,spread=)

X = clf.df[clf.feature_names]
y = clf.df[clf.target_name]
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

y_pred = clf.predict(X_test)


from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

C:\Users\Krisent\PycharmProjects\SystemyRozmyteProjekt\.venv\lib\site-packages\sklearn\base.py:484: FutureWarning: `BaseEstimator._check_n_features` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation._check_n_features` instead.
  warnings.warn(
C:\Users\Krisent\PycharmProjects\SystemyRozmyteProjekt\.venv\lib\site-packages\sklearn\base.py:493: FutureWarning: `BaseEstimator._check_feature_names` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation._check_feature_names` instead.
  warnings.warn(

  ____  __  _  _  ____  ____  _  _  __
 / ___)(  )( \/ )(  _ \(  __)/ )( \(  ) v2.12.0
 \___ \ )( / \/ \ ) __/ ) _) ) \/ (/ (_/\
 (____/(__)\_)(_/(__)  (__)  \____/\____/

 https://github.com/aresio/simpful

              precision    recall  f1-score   support

           0       1.00      0.90      0.95       185
           1       0.96      0.70      0.81       132
           2       0.77      0.83      0.80       217
           3       0.80      0.94      0.86       217

    accuracy                           0.85       751
   macro avg       0.88      0.84      0.85       751
weighted avg       0.87      0.85      0.86       751

In [3]:
X_test

,S1_Temp,S2_Temp,S3_Temp,S4_Temp,S1_Light,S2_Light,S3_Light,S4_Light,S1_Sound,S2_Sound,S3_Sound,S4_Sound,S5_CO2,S5_CO2_Slope,S7_PIR
123,25.56,25.75,25.00,25.88,155,233,74,56,0.50,0.10,0.11,0.08,560,2.653846,0
843,26.25,26.63,25.94,26.38,150,236,180,10,0.90,0.69,1.33,0.88,1105,2.419231,1
3018,25.94,25.94,25.38,26.25,160,249,78,58,0.75,1.12,0.48,0.35,500,2.580769,0
3367,26.06,26.81,25.50,26.31,117,21,25,18,0.12,0.11,0.06,0.06,530,1.253846,0
9121,25.25,25.25,24.81,25.31,0,0,0,0,0.07,0.04,0.06,0.08,345,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6928,25.38,25.38,25.00,25.88,0,0,0,0,0.08,0.05,0.06,0.11,355,0.000000,0
3895,25.81,25.75,25.44,26.06,0,0,0,0,0.07,0.05,0.06,0.07,735,-2.092308,0
8216,25.81,26.00,25.69,25.81,5,5,31,17,0.19,0.27,0.47,0.17,635,2.742308,1
6324,25.44,25.44,25.25,26.00,0,0,0,0,0.08,0.06,0.06,0.10,350,0.000000,0
816,26.25,26.38,26.00,26.50,147,234,177,10,0.66,0.80,2.21,0.68,1055,2.730769,1

In [3]:


df = pd.read_csv("data/Occupancy_Estimation.csv")
target_name ="Room_Occupancy_Count"
df = df.drop(columns=["Date", "Time"])

def under_sample(target_df):
    X = target_df.drop(columns=[target_name])
    y = target_df[target_name]
    rus = RandomUnderSampler(
        sampling_strategy={0: 600},
        random_state=42
    )

    X_res, y_res = rus.fit_resample(X, y)
    return  pd.concat([X_res, y_res], axis=1)
df = under_sample(df)
data_groups = {}
class_names = df[target_name].value_counts().index.tolist()
class_names = sorted(class_names)
for c in class_names:
    data_groups[c] = df[df[target_name] == c]


feature_names = [col for col in df.columns if col != target_name]

C:\Users\Krisent\PycharmProjects\SystemyRozmyteProjekt\.venv\lib\site-packages\sklearn\base.py:484: FutureWarning: `BaseEstimator._check_n_features` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation._check_n_features` instead.
  warnings.warn(
C:\Users\Krisent\PycharmProjects\SystemyRozmyteProjekt\.venv\lib\site-packages\sklearn\base.py:493: FutureWarning: `BaseEstimator._check_feature_names` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation._check_feature_names` instead.
  warnings.warn(

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

# Split data
X = df[feature_names]
y = df[target_name]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Predict function
def predict(X_data):
    preds = []
    for idx, row in X_data.iterrows():
        for feat in feature_names:
            FS.set_variable(feat, row[feat])
        result = FS.Mamdani_inference(['occupancy'])
        preds.append(round(result['occupancy']))
    return preds
# Evaluate
y_pred = predict(X_test)
print(classification_report(y_test, y_pred))

NameError: name 'FS' is not defined

In [105]:





fuzzy_sets = {}
FS = sf.FuzzySystem(operators=['AND_PRODUCT'])
for feature in feature_names:
    fuzzy_sets[feature] = {}
    for c_name in class_names:
        avg = data_groups[c_name][feature].mean()
        std = max(data_groups[c_name][feature].std(),1e-6)
        fuzzy_sets[feature][c_name] = FuzzySet(function=Gaussian_MF(mu=avg,sigma=std),term=f"{c_name}_{feature}")
    FS.add_linguistic_variable(feature, sf.LinguisticVariable(list(fuzzy_sets[feature].values())))


output_sets = []
for c_name in class_names:
    spread = 0.05
    singleton = sf.FuzzySet(
        points=[[c_name - spread, 0], [c_name, 1], [c_name + spread, 0]],
        term=f"class_{c_name}"
    )
    output_sets.append(singleton)

FS.add_linguistic_variable(
    "occupancy",
    sf.LinguisticVariable(output_sets, universe_of_discourse=[0, 3]))

rules = []
for c_name in class_names:
    conds = []
    for feature in feature_names:
        conds.append(f"({feature} IS {c_name}_{feature})")
    conds = " AND ".join(conds)
    rule = f"IF ({conds}) THEN (occupancy IS class_{c_name})"
    rules.append(rule)
FS.add_rules(rules)

  ____  __  _  _  ____  ____  _  _  __
 / ___)(  )( \/ )(  _ \(  __)/ )( \(  ) v2.12.0
 \___ \ )( / \/ \ ) __/ ) _) ) \/ (/ (_/\
 (____/(__)\_)(_/(__)  (__)  \____/\____/

 https://github.com/aresio/simpful

C:\Users\Krisent\PycharmProjects\SystemyRozmyteProjekt\.venv\lib\site-packages\sklearn\base.py:484: FutureWarning: `BaseEstimator._check_n_features` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation._check_n_features` instead.
  warnings.warn(
C:\Users\Krisent\PycharmProjects\SystemyRozmyteProjekt\.venv\lib\site-packages\sklearn\base.py:493: FutureWarning: `BaseEstimator._check_feature_names` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation._check_feature_names` instead.
  warnings.warn(
C:\Users\Krisent\PycharmProjects\SystemyRozmyteProjekt\.venv\lib\site-packages\simpful\simpful.py:292: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

  ____  __  _  _  ____  ____  _  _  __
 / ___)(  )( \/ )(  _ \(  __)/ )( \(  ) v2.12.0
 \___ \ )( / \/ \ ) __/ ) _) ) \/ (/ (_/\
 (____/(__)\_)(_/(__)  (__)  \____/\____/

 https://github.com/aresio/simpful

              precision    recall  f1-score   support

           0       1.00      0.90      0.95       185
           1       0.96      0.70      0.81       132
           2       0.75      0.64      0.69       217
           3       0.70      0.99      0.82       217

    accuracy                           0.81       751
   macro avg       0.85      0.80      0.82       751
weighted avg       0.83      0.81      0.81       751

In [17]:
v = X_test.iloc[[1]].copy()

v['S1_Temp'] = 25.81
v['S2_Temp'] = 26.06
v['S3_Temp'] = 25.75
v['S4_Temp'] = 25.94
v['S1_Light'] = 3
v['S2_Light'] =3
v['S3_Light'] =19
v['S4_Light'] =12
v['S1_Sound'] =0.09
v['S2_Sound'] =0.04
v['S3_Sound'] =0.07
v['S4_Sound'] =0.10
v['S5_CO2'] =750
v['S5_CO2_Slope'] =2.79
v['S6_PIR']= True
v['S7_PIR']= True


clf.predict(v)
v

,S1_Temp,S2_Temp,S3_Temp,S4_Temp,S1_Light,S2_Light,S3_Light,S4_Light,S1_Sound,S2_Sound,S3_Sound,S4_Sound,S5_CO2,S5_CO2_Slope,S6_PIR,S7_PIR
843,25.81,26.06,25.75,25.94,3,3,19,12,0.09,0.04,0.07,0.1,750,2.79,True,True